name: |-
  Main branch workflow

  Build, test Docker image, and deploy it with ecspresso into the `dev` environment and draft new release

  ### Usage

  Create in your repo  __`.github/workflows/main.yaml`__

  ```yaml
    name: Main Branch
    on:
      push:
        branches: [ master ]

    jobs:
      do:
        uses: ./.github/workflows/ecspresso-main-branch.yml
        with:
          organization: "$\{\{ github.event.repository.owner.login }}"
          repository: "$\{\{ github.event.repository.name }}"
        secrets:
          github-private-actions-pat: "$\{\{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}"
          registry: "$\{\{ secrets.ECR_REGISTRY }}"
          secret-outputs-passphrase: "$\{\{ secrets.GHA_SECRET_OUTPUT_PASSPHRASE }}"
          ecr-region: "$\{\{ secrets.ECR_REGION }}"
          ecr-iam-role: "$\{\{ secrets.ECR_IAM_ROLE }}"
  ```

on:
  workflow_call:
    inputs:
      organization:
        description: "Repository owner organization (ex. acme for repo acme/example)"
        required: false
        default: ${{ github.event.repository.owner.login }}
        type: string
      repository:
        description: "Repository name (ex. example for repo acme/example)"
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      enable-migration:
        description: "Run DB migration"
        type: boolean
        required: false
        default: false
      support-rollback:
        description: "Perform rollback on failure"
        type: boolean
        required: false
        default: false
      image-name:
        description: "Image name (excluding registry). Defaults to {{$organization/$repository}}."
        required: false
        type: string
        default: ''
      app:
        description: "Application name. Used with monorepo pattern when there are several applications in the repo"
        required: false
        type: string

      migration-env-overrides:
        description: "Array of KeyValuePairs to override env vars in the migration step."
        required: false
        type: string

    secrets:
      secret-outputs-passphrase:
        description: "Passphrase to encrypt/decrypt secret outputs with gpg. For more information [read](https://github.com/cloudposse/github-action-secret-outputs)"
        required: true
      registry:
        description: "ECR ARN"
        required: true
      github-private-actions-pat:
        description: "Github PAT allow to pull private repos"
        required: true
      ecr-region:
        description: "ECR AWS region"
        required: true
      ecr-iam-role:
        description: "IAM Role ARN provide ECR write/read access"
        required: true
      ssh-private-key:
        required: false
      release-please-token:
        required: true

jobs:
  ci:
    uses: ./.github/workflows/workflow-ci-dockerized-app-build.yml
    with:
      organization: ${{ inputs.organization }}
      repository: ${{ inputs.repository }}
      image-name: ${{ inputs.image-name }}
      build-args: "BUILD_ENV=deploy"
    secrets:
      ecr-region: ${{ secrets.ecr-region }}
      ecr-iam-role: ${{ secrets.ecr-iam-role }}
      registry: ${{ secrets.registry }}
      secret-outputs-passphrase: ${{ secrets.secret-outputs-passphrase }}
      ssh-private-key: ${{ secrets.ssh-private-key }}

  cd:
    uses: ./.github/workflows/workflow-cd-ecspresso.yml
    needs: [ ci ]
    with:
      image: ${{ needs.ci.outputs.image }}
      tag: ${{ needs.ci.outputs.tag }}
      repository: ${{ inputs.repository }}
      environment: dev
      enable-migration: ${{ inputs.enable-migration }}
      migration-env-overrides: ${{ inputs.migration-env-overrides }}
      support-rollback: ${{ inputs.support-rollback }}
      app: ${{ inputs.app }}
    secrets:
      secret-outputs-passphrase: "${{ secrets.secret-outputs-passphrase }}"
      github-private-actions-pat: "${{ secrets.github-private-actions-pat }}"

  release-please:
    runs-on: ubuntu-latest
    needs: [cd]
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.release-please-token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
